package org.tat.gginl.api.domains.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.tat.gginl.api.domains.Product;

public interface ProductRepository extends JpaRepository<Product, String>{
	String query = "SELECT RTRIM([ID]) AS ID,RTRIM([NAME]) AS NAME,RTRIM([PRODUCTGROUPID]) AS PRODUCTGROUPID,RTRIM([AUTOCALCULATE]) AS AUTOCALCULATE,RTRIM([FIXEDVALUE]) AS FIXEDVALUE,RTRIM([PREMIUMRATETYPE]) AS PREMIUMRATETYPE,RTRIM([BASESUMINSURED]) AS BASESUMINSURED,RTRIM([STANDARDEXCESS]) AS STANDARDEXCESS,RTRIM([FIRSTCOMMISSION]) AS FIRSTCOMMISSION,RTRIM([RENEWALCOMMISSION]) AS RENEWALCOMMISSION,RTRIM([MAXSUMINSURED]) AS MAXSUMINSURED,RTRIM([MINSUMINSURED]) AS MINSUMINSURED,RTRIM([MAXTERM]) AS MAXTERM,RTRIM([MINTERM]) AS MINTERM,RTRIM([INSURANCETYPE]) AS INSURANCETYPE,RTRIM([CREATEDUSERID]) AS CREATEDUSERID,RTRIM([CREATEDDATE]) AS CREATEDDATE,RTRIM([UPDATEDUSERID]) AS UPDATEDUSERID,RTRIM([UPDATEDDATE]) AS UPDATEDDATE,RTRIM([VERSION]) AS VERSION,RTRIM([CURRENCYID]) AS CURRENCYID,RTRIM([MULTICURPREFIX]) AS MULTICURPREFIX,RTRIM([PREFIX]) AS PREFIX,RTRIM([MAXUNIT]) AS MAXUNIT,RTRIM([MAXAGE]) AS MAXAGE,RTRIM([MINAGE]) AS MINAGE,RTRIM([MAXHOSPDAYS]) AS MAXHOSPDAYS,RTRIM([ENTEREDPERCENT]) AS ENTEREDPERCENT" + 
			"  FROM PRODUCT";
	
	@Query(value = query,nativeQuery = true)
	List<Object[]> findAllNativeObject();
	
	@Query(value = "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PRODUCT'",nativeQuery = true)
	List<Object> findAllColumnName();

}
